### ISSUE TITLE
BindingBehavior Validation is ambiguous

### ISSUE THREAD

**Issue by Kiskae** [sk89q/Intake#1]
The BindingBehavior used in the definition of custom parameters exhibits some weird validation that I do not believe is correct.

The following table shows the BindingBehavior, the given number of consumed arguments and whether the validator ([ParameterData.java#L160](https://github.com/sk89q/Intake/blob/master/src/main/java/com/sk89q/intake/parametric/ParameterData.java#L160)) will allow it.

| BindingBehavior | -1 | 0 | > 0 |
| --- | --- | --- | --- |
| CONSUMES | Allowed   | Error | Allowed  |
| INDETERMINATE | Allowed | Error | Error  |
| PROVIDES | Allowed  | Error  | Error  |

This might seem correct, but the check at [ParameterData.java#L186](https://github.com/sk89q/Intake/blob/master/src/main/java/com/sk89q/intake/parametric/ParameterData.java#L186) leads me to assume that PROVIDES is allowed to have a consuming count of 0.

A clarification would be appreciated and if my assumption is true, the validation will need to be changed.

**Comment by sk89q** [comment]
Fixed since I threw all of this away for 4.x. Itmight need to make a return in the future if I add back support for optional parameters that don't occur at the end.
