### ISSUE TITLE
Examples not resolving guava classes

### ISSUE THREAD

**Issue by Favorlock** [sk89q/Intake#24]
Just cloned a fresh copy of the repo and gradle is unable to resolve the google classes for the examples. http://i.imgur.com/JcOQL6c.png

**Comment by sk89q** [comment]
I'm not sure to be honest. It looks like the dependencies aren't being shared transitively, maybe?

First, try clearing the cache for IntelliJ IDEA via the File menu and restarting.

I've had IntelliJ IDEA go nuts on project configuration and force me to reimport the entire project on more than one occasion. You might want to try that second.

Workarounds:

1. Replace `Sets.newHashSet()` with `new HashSet<>()`. The call to `Sets` is not as relevant for the more recent versions of Java.
2. Manually add the dependency to the example project via the File -> Module Settings window.

**Comment by Favorlock** [comment]
Ok, I just manually added the dependencies. By the way, are there any major updates planned for Intake soon? It looks like it's been a while since the last push.

**Comment by sk89q** [comment]
I don't know if it will be soon, but there may be a major breaking update at some point most likely.

Last year for WorldEdit, I unified argument parsers and commands into one single construct and got rid of the annotations, which greatly simplified everything, and mostly importantly it significantly helped reusability.

With it, I was able to implement both `//set` and the shape brushes with minimal code duplication:

* //set: `new SelectionCommand(new ApplyCommand(new ReplaceParser(), "Set all blocks within selection"), "worldedit.region.set"))`
* Brushes: `new ShapedBrushCommand(new ApplyCommand(new ReplaceParser(), "Set all blocks within region"), "worldedit.brush.set"))`

As you see, ReplaceParser and ApplyCommand are reused between both.

However, these changes would break pretty much all existing uses of the library and so it would be a new major release.

**Comment by Favorlock** [comment]
That's pretty nifty. I'm looking into using Intake for one of my network projects right now as it seems to accomplish what I'd like to get out of a command system without the need to write everything from scratch, so I'm definitely interested in seeing what changes are made in the future.

Also, I think your wiki documentation needs updating to match the current usage.
