### ISSUE TITLE
Switch to a newer java version

### ISSUE THREAD

**Issue by Stupremee** [sk89q/Intake#28]
Some reasons why to switch to Java 11:
- LTS Version
- New language features
- Optimum performance
- Writing code more efficiently
- Oracle recommendation to uninstall pre-8 versions to avoid security risks
- Older releases no longer publicly supported
- Third party Java libraries no longer being developed and supported

**Comment by wizjany** [comment]
1) Intake is not really under development anymore.
2) People using Intake for Minecraft (i.e. most of them, probably) still have to target Java 8.
3) Unless there's a particular issue, Intake will still run under newer versions of Java.
