### ISSUE TITLE
ParametricCallable tries to conveter thrown CommandExceptions

### ISSUE THREAD

**Issue by TheE** [sk89q/Intake#5]
Supposed we have a method where a `CommandException` is thrown when some sort of custom validation fails:
````JAVA
@Command(aliases = {"sqlite"}, desc = "import.sqlite.description")
public void sqlite(Actor actor, String databasePath) throws CommandException {
  File database = new File(getDataFolder(), databasePath);
  if (!database.exists()) {
    throw new CommandException("The database file '" + database.getAbsolutePath() + "' does not exist."));
  }
  migrate(actor, database);
}
````
If this method is called by a `ParametricCallable` (after it has been created by the `ParametricBuilder`), the `CommandException` gets wrapped in a `InvocationTargetException`.

This behaviour leads to a call to the registered ExceptionConverters to convert the exception (see [here](https://github.com/sk89q/Intake/blob/master/src/main/java/com/sk89q/intake/parametric/ParametricCallable.java#L273)). I believe there is no need to look for a conversion where instead the CommandException could be thrown directly since this is already the type of Exception that is expected.

**Comment by sk89q** [comment]
Fixed now afaik.
